### ISSUE TITLE
rake aborted! No Rakefile found (looking for: rakefile, Rakefile, rakefile.rb, Rakefile.rb)

### ISSUE THREAD

**Issue by sadiqmmm** [oriontransfer/financier#9]
I followed the instructions of **Installation** and **usage**.

When running the command 

**rake financier:users:create**
_or_ 
**rake**
I am getting this following _error_.

```
rake aborted!
No Rakefile found (looking for: rakefile, Rakefile, rakefile.rb, Rakefile.rb)
```

**Comment by ioquatix** [comment]
Sorry, this documentation is out of date.

**Comment by ioquatix** [comment]
I've updated the documentation and added the base/bare site in `example/`. Please try it and let me know.

**Comment by sadiqmmm** [comment]
Thanks for reply. It is working now. :)

**Comment by ioquatix** [comment]
Awesome.

I've been using this system for two companies, one for over 10 years. It's robust, but at some point in the future I think I'll consider migrating to Postgres. While I'll provide a migration path (for my own data etc), it may be non-trivial. That being said, I want to continue working on this system where it makes sense.

**Comment by sadiqmmm** [comment]
Thank you for the information. You're really an amazing person. Your open source contributions are amazing.
